### ISSUE TITLE
[feat] Redirect to another webpage

### ISSUE THREAD

**Issue by get6** [get6/get6.github.io#15]
## 📢 Description

해당 위치에서 다른 페이지로 보냅니다.

## 💎 Requirements

클릭한 곳을 다시 클릭해도 새로고침되거나 이동되지 않습니다.
next/link에 Link 컴포넌트를 사용합니다.
`/books`, `/series`, `/tags`, `/about`에 해당하는 tsx 파일이 필요합니다.

## ✨ Todo

- [x] 이동할 위치에 해당하는 페이지 생성
- [x] 선택된 상태에서는 파란색 텍스트와 파란색 밑줄이 나옵니다
- [x] 마우스 호버에서는 선택된 상태처럼 색이 바뀌고 밑줄이 나옵니다
